name: CI

on:
  push:
    branches:
    - main
  pull_request:

env:
  # The NAME makes it easier to copy/paste snippets from other CI configs
  NAME: souffle-lint

jobs:
  deb:
    # This job currently takes longer than the `test` job. To keep CI times low
    # for pull requests while maintaining our ability to catch problems before
    # releases, we only run it on main.
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deps
      run: |
        sudo apt-get install -y musl-tools
        rustup target add x86_64-unknown-linux-musl
        cargo install cargo-deb
    - uses: Swatinem/rust-cache@v2
    - run: make deb

  doc:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel previous run
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v4

    - name: Build docs
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "doc/"

    - name: Push docs
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: doc/build/html

    - name: Package docs
      shell: bash
      run: |
        tar -cvf doc.tar.gz doc/build/html/*

    - name: Upload docs
      uses: actions/upload-artifact@v3
      if: github.repository == 'langston-barrett/souffle-lint'
      with:
        name: "${{ env.NAME }}-docs"
        path: "*.tar.gz"
        if-no-files-found: error

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Format
      run: cargo fmt && git diff --exit-code
    - name: Deps
      run: |
        rustup update
        rustup component add clippy
    - uses: Swatinem/rust-cache@v2
    - name: Lint
      run: make CARGO_FLAGS=--no-default-features lint

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build deps
      run: |
        pip install -r doc/requirements.txt

    - run: make CARGO_FLAGS=--locked build

    - name: Test deps
      run: |
        pip install lit==15
        sudo apt-get install -y llvm-11-tools
        sudo update-alternatives --install /usr/bin/FileCheck FileCheck /usr/bin/FileCheck-11 60

    - uses: Swatinem/rust-cache@v2

    - run: make CARGO_FLAGS=--locked test
