on:
  push:
    tags:
    - 'v*'

name: release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Deps
      run: |
        sudo apt-get install -y musl-tools
        rustup target add x86_64-unknown-linux-musl

    - name: Build static executable
      run: |
        make static
        cp target/x86_64-unknown-linux-musl/release/souffle-lint .

    - name: Build Debian package
      run: |
        make deb
        cp target/debian/souffle-lint_*_amd64.deb .

    - uses: ncipollo/release-action@v1
      with:
        artifacts:
        - "souffle-lint"
        - "souffle-lint_*_amd64.deb"
        body: "See [CHANGELOG.md](https://github.com/langston-barrett/souffle-lint/blob/main/CHANGELOG.md)"
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}
