name: release

on:
  push:
    branches:
    - release*
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Deps
      run: |
        sudo apt-get install -y musl-tools
        rustup target add x86_64-unknown-linux-musl
        cargo install cargo-deb

    - name: Build static executable
      run: |
        make CARGO_FLAGS=--locked static
        cp target/x86_64-unknown-linux-musl/release/souffle-lint .

    - name: Build Debian package
      run: |
        make deb
        cp target/debian/souffle-lint_*_amd64.deb .

    - uses: ncipollo/release-action@v1
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      with:
        artifacts: "souffle-lint,souffle-lint_*_amd64.deb"
        artifactErrorsFailBuild: true
        body: "See [CHANGELOG.md](https://github.com/langston-barrett/souffle-lint/blob/main/CHANGELOG.md)"
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to crates.io
      env:
        CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        # Only push on actual release tags
        PUSH: ${{ startsWith(github.ref, 'refs/tags/v') }}
      # TODO(#29): Enable features
      run: |
        if [[ ${PUSH} == true ]]; then
          cargo publish --locked --token ${CRATES_IO_TOKEN} --no-default-features
        else
          cargo publish --locked --dry-run --token ${CRATES_IO_TOKEN} --no-default-features
        fi
